### ISSUE TITLE
DankNull loop crash the client

### ISSUE THREAD

**Issue by teutates1989** [p455w0rd/DankNull#163]
**Mod version**

DankNull-1.12-1.4.43

**Can the issue be reproduced?**
unknown

**Logs**
https://pastebin.com/z9dvNvwv

**Issue**
i had a crash while scrolling my DankNull in the enigmatic expert pack. 
But every relog i had the same crash. with some admins killing me to end this loop.
But when i try to open my old grave i get the same crash.

**Comment by Aerophite** [comment]
This has happened to me twice now. For me, and it looks like for you too, it's the "architecturecraft" item. Once it becomes "selected" by the DankNull, you enter this crash loop.

#155

**Comment by DarkSeplep** [comment]
same issue with other kind of items in it. 
[crash-danknull.txt](https://github.com/p455w0rd/DankNull/files/2959090/crash-danknull.txt)

**Comment by StefanTT** [comment]
I can confirm the issue.
Opening the player's inventory that contains the DankNull crashes the client. Opening a machine that also displays the inventory also crashes the client.

I had some architecture craft slants in the DankNull.
Disabling architecturecraft finally fixed the crashes. Fortunately my world only contained very few architecturecraft elements so it was not that big of a loss.

Interestingly there is no crash as long as the architecturecraft item is not selected by the dank, as others have reported above.

**Comment by p455w0rd** [comment]
can someone tell me if this is still an issue in latest version?

**Comment by StefanTT** [comment]
Should it be fixed now?

**Comment by Penetrosity** [comment]
Just commenting to confirm that this issue exists as of the last version in Enigmatica 2:Expert which my version had:
architecturecraft-1.12-3.80.jar
DankNull-1.12-1.4.43.jar

I'm not an expert at NBTExplorer, but deleting it from my player.dat, or removing my whole player folder (or just player.dat) didn't resolve it. Trying the setting in codechickenlib suggested elsewhere ```B:"attemptRecoveryOnItemRenderException"=false ``` to true did not work either. I've since decided to simply udpate to 1.67 which removes dank/null and hope that works (If anyone finds themselves in a very similar spot to me)
