### ISSUE TITLE
Scrolling to an unsupported item crashes the game.

### ISSUE THREAD

**Issue by Rainy-Night1** [p455w0rd/DankNull#92]
On FTB Revelations, scrolled through a diamond dank null and upon reaching a certain item (didnt get to see it) it crashed my game, and kept crashing on login since rendering this item crashes the game, this bug locked me out of the world.

Crash log:
https://pastebin.com/2iB4EhNa

**Comment by p455w0rd** [comment]
can u try updating to latest version available on Curse and tell me if this still happens?

**Comment by Rainy-Night1** [comment]
Looks like Architecturecraft blocks stored in the dank/null are causing this. Couldn't try to update to latest version as this was on a server that I don't own or manage so I had to try to replicate the bug. What I've found is that holding any type of dank null and scrolling to Architecturecraft modified blocks that come from the Sawbench (as seen here https://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ArchitectureCraft/Doc/UserManual.html) will crash the game. Then just having the dank null in your inventory will continue to crash whenever you log in. Rendering the dank null in any way will continue to crash the game (in a chest, on the ground, still crashes) 

I have updated /dank/null and your library and the same crash still happens. Here is the crash log on the latest version, hope this helps. For now I'll make sure to not store any Architecturecraft blocks in a dank null.
https://pastebin.com/VFZKfZq2

**Comment by p455w0rd** [comment]
the reason i needed a crash log from the latest version is so that the line number in the crash log will match my code..in the first crash log that line in code didn't have the possibility of being null..new crash i believe is accurate (up to date), so I'll make sure this gets fixed in next update

**Comment by p455w0rd** [comment]
the version of architecturecraft you have is also out of date - latest is here: https://minecraft.curseforge.com/projects/architecturecraft-elytradev/files/2525508 - i hate to be a pain like this, but in order for me to even begin discussion with another dev, I have to be certain that this is an existing bug in current versions...I'm also having a rough time getting this mod to work in dev without it vomiting a ton of errors and constantly crashing..doesn't seem to be very stable for a pack environment (I'm sure it works great in dev by itself)...on top of all of this, FTB is pretty notorious for taking their sweet time updating packs...i'll also be testing this myself when I get time, I just have several updates I need to get out today, so I don't know how soon I can get to this

**Comment by p455w0rd** [comment]
Fixed in coming update :)
![](https://i.imgur.com/TmmleET.png)

**Comment by ttamnedlog** [comment]
Just wanted to chime in and say it's not restricted to Architecturecraft. My friend on my FTB Revelation server said his emerald dank caused him to crash when he put an opaque itemduct (Thermal Expansion) in it. He's running the FTB Revelation pack out of the box, with no additional mods.

I don't have _his_ crash report, but I just went into a single player creative world, gave myself an emerald dank and an opaque itemduct, dropped it in and crashed immediately. Here's my crash report (though I am running optifine):

https://pastebin.com/LwrBaTaM

**Comment by p455w0rd** [comment]
@ttamnedlog have you tried this version: https://minecraft.curseforge.com/projects/wireless-crafting-terminal/files/2538109 ? the FTB team can be slow at updating..try this version locally and if you can, and let me know how it goes

**Comment by ttamnedlog** [comment]
@p455w0rd You linked to the Wireless Crafting Terminal mod. Not sure if that was a mistake or if that's related. Just in case, I updated both it and Dank Null, and removed Optifine for good measure. Still crashed immediately upon placing an opaque itemduct in a dank null. I was curious if it was strictly related to the emerald dank or if it applied to others. I tried with an iron one and still crashed.

https://pastebin.com/5MMc7Q4Q

I did also test with an Architecturecraft block, using those new versions of your mod and Wireless Crafting Terminal, and got no crashes there.

I'll remove _all other_ mods and test it with just Dank Null and Thermal Dynamics (and its dependencies) and report back!

**Comment by ttamnedlog** [comment]
One more crash report, unless you have further suggestions of configurations to test. Happy to help!

https://pastebin.com/s0i1v1nz

This time I just had your mod and dependencies, Thermal Dynamics and dependencies, and tested with opaque itemduct and the redstone dank null.

**Comment by p455w0rd** [comment]
yeah...i was confused lol...looking into this now..but with the fix implemented for the ArchitectureCraft, this should be fixed as well..this update isn't on curse yet..still working on networking..thanks for reporting tho

**Comment by ttamnedlog** [comment]
Happy to help!

Is it worth noting that I _didn't_ crash when scrolling to an ArchitectureCraft block using the most recent curse version of your mod?

Granted, I may have just happened to choose an ArchitectureCraft block that never had a problem to begin with, and I may have not otherwise taken the proper steps to reproduce that problem. I just grabbed a block out of JEI; I didn't actually create the block on the Sawbench. If that makes a difference.

**Comment by p455w0rd** [comment]
@ttamnedlog your issue actually was different, but I got it fixed :D
![](https://i.imgur.com/kxYPgQF.png)

**Comment by ProsperCraft** [comment]
Here is another one for you, thermal expansion ducts as well - https://gist.github.com/chayde/8366bf72a0b7348aceb6ff18c1b43453
